feat: global ethclient
RSS3-Network/DSL-v0.4 pull request #160
Opened 2022-08-25 19:31 UTC by HenryQW

2022-08-26 01:41 UTC, kallydev requested changes

2022-08-26 01:41 UTC, kallydev commented on service/indexer/internal/datasource/alchemy/datasource.go
> -	if internalDatasource.ethereumClientMap[protocol.NetworkPolygon], err = ethclient.Dial(config.General.Polygon.HTTP); err != nil {
Polygon also uses alchemy.

2022-08-26 01:41 UTC, kallydev commented on service/hub/internal/server/server.go
> +	ethereumClientMap, err := ethclientx.Dial(config.ConfigHub.RPC, []string{protocol.NetworkEthereum, protocol.NetworkPolygon})
The `ResolveCrossbell` function uses the Crossbell RPC, but the Hub does not initialize it.

```diff
func ResolveCrossbell(input string) (string, error) {
 	var result string
- 	ethereumClient, err := ethclient.Dial(config.ConfigHub.RPC.General.Crossbell.HTTP)
+ 	ethereumClient, err := ethclientx.Global(protocol.NetworkCrossbell)
 	if err != nil {
 		return "", fmt.Errorf("failed to connect to crossbell rpc: %s", err)
 	}
}
```

2022-08-26 01:41 UTC, kallydev commented on service/indexer/internal/worker/exchange/swap/worker_test.go
> +	ethereumClientMap, err := ethclientx.Dial(&configx.RPC{
Missing networks parameter?

2022-08-26 01:41 UTC, kallydev commented on service/indexer/internal/worker/social/crossbell/worker.go
> +	if s.ethereumClient, err = ethclientx.Global(s.Networks()[0]); err != nil {
~Why not use the global ethereum client?~ Why not just use the global ethereum client?

2022-08-26 01:41 UTC, kallydev commented on service/indexer/internal/worker/exchange/swap/worker.go
> -		ethereumClientMap: make(map[string]*ethclient.Client),
`ethereumClientMap` still exists within the `service` structure.

2022-08-30 15:43 UTC, HenryQW commented on service/indexer/internal/worker/social/crossbell/worker.go
> +	if s.ethereumClient, err = ethclientx.Global(s.Networks()[0]); err != nil {
handler still needs to initialize with an ethclient, trying the keep the changes to the minimal 👀

2022-08-30 15:45 UTC, HenryQW commented on service/indexer/internal/datasource/alchemy/datasource.go
> -	if internalDatasource.ethereumClientMap[protocol.NetworkPolygon], err = ethclient.Dial(config.General.Polygon.HTTP); err != nil {
it was dialed after line 243, github didn't show them 👀

2022-09-09 20:15 UTC, brucexc approved these changes

2022-09-12 23:43 UTC, merged