partybid support
RSS3-Network/DSL-v0.4 pull request #190
Opened 2022-09-20 04:11 UTC by brucexc

- add partybid as crowdfunding type
- add partybid tx actions including start, contribute, buy(bid), expire(finalize), claim

2022-09-20 17:56 UTC, HenryQW requested changes

2022-09-20 17:56 UTC, HenryQW commented on common/protocol/filter/type.go
>  	// NFT types
hub没有支持新类型的过滤
<img width="894" alt="image" src="https://user-images.githubusercontent.com/5896343/191318498-b8bfa33f-0daf-4390-abfc-9ba464150038.png">

2022-09-20 17:56 UTC, HenryQW commented on common/database/model/metadata/collectible.go
> +	EthSpent         decimal.Decimal `json:"eth_spent"`
这里可以复用 common/database/model/metadata/metadata.Token 的结构

2022-09-20 17:56 UTC, HenryQW commented on common/database/model/metadata/collectible.go
> +	EthFeePaid       decimal.Decimal `json:"eth_fee_paid"`
这里的fee是指gas吗？
<img width="978" alt="image" src="https://user-images.githubusercontent.com/5896343/191319660-68afe5ed-5d5c-4f48-86e7-bc7a044b67b1.png">

2022-09-20 17:56 UTC, HenryQW commented on common/database/model/metadata/collectible.go
> +	MarketWrapper string           `json:"market_wrapper"`
market_wrapper是指交易实际发生的平台吧？有没有更适合的名字？marketplace, trading_platform之类的

2022-09-20 17:56 UTC, HenryQW commented on common/database/model/metadata/collectible.go
> +	TokenId       string           `json:"nft_token_id,omitempty"`
`nft_`前缀可以去掉，和其他保持一致。
`party_`前缀感觉也可以去掉，已经在party里面了感觉有点累赘。

2022-09-20 18:38 UTC, brucexc commented on common/database/model/metadata/collectible.go
> +	EthFeePaid       decimal.Decimal `json:"eth_fee_paid"`
fee: transaction fee
eth_spent: 在partybid上购买这个NFT所花费的eth
eth_fee_paid: 支付给partybid的手续费 总价*2.5%

2022-09-20 18:48 UTC, brucexc commented on common/database/model/metadata/collectible.go
> +	EthSpent         decimal.Decimal `json:"eth_spent"`
感觉复用程度不高。如果展示fractional后的token可以复用

2022-09-21 12:22 UTC, HenryQW commented on common/database/model/metadata/collectible.go
> +	EthFeePaid       decimal.Decimal `json:"eth_fee_paid"`
eth_spent： 就应该用token结构了
eth_fee_paid：也一样，名字可以改成 platform_fee/trading_fee 之类的？

2022-10-06 15:16 UTC, HenryQW commented
🎉 perfect

2023-10-11 19:45 UTC, closed without merging