Feat/ethereum get asset transfers
RSS3-Network/DSL-v0.4 pull request #197
Opened 2022-09-26 03:49 UTC by brucexc

- add getAssetTransfers func from datasource etl to replace alchemy

2022-09-26 12:18 UTC, kallydev requested changes

2022-09-26 12:18 UTC, kallydev commented on common/datasource/pregod_etl/ethereum/client.go
> +	Hash     []byte  `gorm:"column:hash"`
`common.Hash`

2022-09-26 12:18 UTC, kallydev commented on common/datasource/pregod_etl/ethereum/client.go
> +	From     []byte  `gorm:"column:from_address"`
`common.Address`

2022-09-26 12:18 UTC, kallydev commented on common/datasource/pregod_etl/ethereum/client.go
> +	err := database.EthDb().
Only transactions from `message.Address` will be fetched here, which will cause the address whitelist to become useless. 🤔

2022-09-26 12:18 UTC, kallydev commented on service/indexer/internal/datasource/pregod_etl/ethereum/datasource.go
> +		if internalTransaction.AddressFrom != "" && !strings.EqualFold(internalTransaction.AddressFrom, message.Address) && !allowlist.AllowList.Contains(internalTransaction.AddressFrom) {
This is the code associated with the whitelist.

2022-09-26 12:18 UTC, kallydev commented on service/indexer/internal/datasource/pregod_etl/ethereum/datasource.go
> +func AppendHexPrefix(hexaString string) string {
[https://github.com/ethereum/go-ethereum/tree/master/common/hexutil](https://github.com/ethereum/go-ethereum/tree/master/common/hexutil).

2022-09-26 16:48 UTC, brucexc commented on common/datasource/pregod_etl/ethereum/client.go
> +	From     []byte  `gorm:"column:from_address"`
if set type to_address as common.Address , error " can't scan []byte of len 0 into Address, want 20" will be existed  when to_address is null

2022-09-26 17:25 UTC, brucexc commented on common/datasource/pregod_etl/ethereum/client.go
> +	err := database.EthDb().
etl don't need to deal with this whitelist logic because neither poap nor lens is on ethereum

2022-09-28 00:33 UTC, kallydev requested changes

2022-09-28 00:33 UTC, kallydev commented on service/indexer/internal/datasource/pregod_etl/ethereum/datasource.go
> +
Why deleted allowlist? 👀

2022-09-28 01:14 UTC, brucexc commented on service/indexer/internal/datasource/pregod_etl/ethereum/datasource.go
> +
i don't think ethereum has poap address in allowlist

2022-09-28 09:16 UTC, polebug commented on common/datasource/pregod_etl/ethereum/client.go
> +	err := database.EthDb().
I think database query should use pagination?

2022-09-28 09:16 UTC, polebug commented on service/indexer/internal/datasource/pregod_etl/ethereum/datasource.go
> +	Source = "ethereum-etl"
maybe use `protocol.SourcePregodETL`
i think lens alse should use it

2022-09-28 09:16 UTC, polebug commented on common/datasource/pregod_etl/ethereum/client.go
> +package ethereum
I don't think there is a need to open a directory for ethereum.
`GetAssetTransfers` is common

2022-09-28 15:57 UTC, brucexc commented on common/datasource/pregod_etl/ethereum/client.go
> +package ethereum
But the current situation is that different network is connected to different ETL source data，which leads to that  GetAssetTransfers is uncommon 🤔

2022-09-28 15:57 UTC, brucexc commented on service/indexer/internal/datasource/pregod_etl/ethereum/datasource.go
> +	Source = "ethereum-etl"
great

2022-09-29 00:37 UTC, merged