update(indexer/crawler): support lens follow and crowdfund platform
RSS3-Network/DSL-v0.4 pull request #322
Opened 2022-11-29 08:10 UTC by polebug

2022-11-29 08:34 UTC, kallydev approved these changes

2022-12-01 15:42 UTC, HenryQW requested changes

2022-12-01 15:42 UTC, HenryQW commented on common/worker/lens/lens.go
>  var SupportLensPlatform = map[string]bool{
列表外的平台也需要索引只是没有related_url

2022-12-02 23:08 UTC, HenryQW requested changes

2022-12-02 23:08 UTC, HenryQW commented on common/worker/lens/lens.go
> +		return fmt.Errorf("not supported")
我试了下还能走合约unfo的，https://polygonscan.com/tx/0x3a1b4229af090229ebf40db9b01910ea7297a7c1aafc19b5ede2e03de9edee25

2022-12-05 02:31 UTC, polebug commented on common/worker/lens/lens.go
> +		return fmt.Errorf("not supported")
这个是就是处理unfo的，followed是处理fo

2022-12-05 08:13 UTC, merged