feat: avvy domains support
RSS3-Network/DSL-v0.4 pull request #326
Opened 2022-11-30 21:13 UTC by brucexc

- add avvy domains support
- add globalEthereumUrlMap

2022-12-01 15:51 UTC, HenryQW requested changes

2022-12-01 15:51 UTC, HenryQW commented on common/worker/name_service/client.go
> +	if success {
value需要检查空值：比如 muafnft.avax 没有绑定EVM地址，https://app.avvy.domains/domains/muafnft.avax

2022-12-01 17:15 UTC, brucexc commented on common/worker/name_service/client.go
> +	if success {
这种情况下 value 赋值给 result 也是为空

2022-12-06 19:02 UTC, HenryQW approved these changes

2022-12-06 19:02 UTC, merged