feat: 你过去提交的内容包含 m 个词，超越了 n% 的用户
RSS3-Network/DSL-v0.4 pull request #338
Opened 2022-12-06 09:58 UTC by sljeff

https://www.notion.so/rss3/social-x-4ec64be6f03146809c3d3d46abac0264

2022-12-06 17:13 UTC, HenryQW requested changes

2022-12-06 17:13 UTC, HenryQW commented on service/hub/internal/server/summary/social_post.go
> +	if err := db.Model(&model.Transfer{}).Select("metadata").Where("address_from = ? AND tag = 'social' AND type = 'post'", address).Scan(&metadata).Error; err != nil {
DATE_PART('year', timestamp) = '2022'

2022-12-06 17:13 UTC, HenryQW commented on service/hub/internal/server/summary/social_post.go
> +	if err := db.Model(&model.Transfer{}).Select("metadata").Where("address_from = ? AND tag = 'social' AND type = 'post'", address).Scan(&metadata).Error; err != nil {
这里的逻辑可以全部移到这里的 `CountSocial` 方法：
<img width="464" alt="image" src="https://user-images.githubusercontent.com/5896343/205977585-b8c5f47c-817e-4aae-9b9e-c178e784c25f.png">

在 `SocialResult` 加俩字段或者结构体：
TotalWord
WordPercentile

2022-12-09 10:12 UTC, sljeff commented
~https://github.com/golang/go/issues/57185~

resolved

2022-12-12 21:54 UTC, HenryQW approved these changes

2022-12-12 21:54 UTC, merged